Issues
frontend-park-mail-ru/2023_2_Rabotyagi pull request #17
Opened 2023-10-07 17:34 UTC by NickDemiman

https://github.com/frontend-park-mail-ru/2023_2_Rabotyagi/issues/16
https://github.com/frontend-park-mail-ru/2023_2_Rabotyagi/issues/10
https://github.com/frontend-park-mail-ru/2023_2_Rabotyagi/issues/8
https://github.com/frontend-park-mail-ru/2023_2_Rabotyagi/issues/7

2023-10-07 17:45 UTC, GreatFix requested changes
Поправить по примеру с телеги

2023-10-07 17:45 UTC, GreatFix commented on src/shared/api/auth.js
> +                if (data.status == 200) {
Не нужно в then проверять статус код (его вообще не нужно проверять), для обработки ошибок есть catch. А также нужно добавлять логику api сервисы, пиши этот then там, где был вызван AUTH_SERVICE.signin()

2023-10-07 17:45 UTC, GreatFix commented on src/shared/api/auth.js
> +    window.AUTH_SERVICE = AUTH_SERVICE;
не стоит все в window писать, экспортируй отсюда и импортируй где нужно

2023-10-07 17:45 UTC, GreatFix commented on src/shared/constants/api.mjs
> +    SIGNUP: ADRESS_BACKEND + 'signup',
Хост (переменная ADRESS_BACKEND ) поставь префиксом внутри ajax сервиса, а не тут

2023-10-07 17:45 UTC, GreatFix commented on src/shared/constants/api.mjs
> +    SIGNUP: ADRESS_BACKEND + 'signup',
само определение оставляешь тут и импортируешь в сервис

2023-10-07 17:45 UTC, GreatFix commented on src/shared/services/ajax.js
> +                if (response.ok) {
В телеге расписал что тут должно быть

2023-10-07 17:45 UTC, GreatFix commented on src/shared/services/ajax.js
> +        async get({url, params}) {
тут можно было оставить как было

2023-10-07 17:45 UTC, GreatFix commented on public/index.html
> +        <script type="module" src="shared/api/auth.js"></script>
Ниже написал, нужно экпорт/импортить в рамках js файлов, а не подключать сюда

2023-10-07 18:20 UTC, GreatFix requested changes

2023-10-07 18:20 UTC, GreatFix commented on src/components/error/errorMessageBox.mjs
> +export const errorMessageBox = (error) => {
Давай с большой буквы, чтобы единообразно делать компоненты. И кстати, желательно, чтобы название файла совпадало с названием компонента (здесь он совпадает, но например в PostCard нет)

2023-10-07 18:20 UTC, GreatFix commented on src/components/feed/feed.mjs
> +                let card = new PostCard(info);
Не забываем юзать `const`

2023-10-07 18:20 UTC, GreatFix commented on src/components/feed/feed.mjs
> +            const response = await POST_SERVICE.feed();
Только вот лоадера не хватает

2023-10-07 18:20 UTC, GreatFix commented on src/shared/api/auth.js
> +            }).then(data => {
Выносим логику редиректа из сервиса

2023-10-07 19:23 UTC, NickDemiman commented on src/shared/constants/api.mjs
> +    SIGNUP: ADRESS_BACKEND + 'signup',
> Хост (переменная ADRESS_BACKEND ) поставь префиксом внутри ajax сервиса, а не тут

тут появляется проблема, из за которой нельзя будет заасайнить значение ADRESS.... другим полям внутри объекта, и чтобы не менять значение адреса в нескольких местах я решил сделать так, всеравно переделать?

2023-10-07 19:54 UTC, GreatFix commented on src/pages/signin.mjs
> +                    await Auth.signin(emailInput.value, passInput.value).then(resp => {
Можно кстати через then. catch написать и не будет нужды в функции

2023-10-07 19:57 UTC, GreatFix commented on src/shared/constants/api.mjs
> +    SIGNUP: ADRESS_BACKEND + 'signup',
не понимаю. Просто в ajax сервисе ставишь перед url эту константу и все

2023-10-07 19:57 UTC, NickDemiman commented on src/shared/constants/api.mjs
> +    SIGNUP: ADRESS_BACKEND + 'signup',
аааа, понял

2023-10-07 20:28 UTC, NickDemiman commented on src/components/feed/feed.mjs
> +            const response = await POST_SERVICE.feed();
сначала не понял, а потом как понял и поправил

2023-10-07 21:20 UTC, GreatFix requested changes

2023-10-07 21:20 UTC, GreatFix commented on src/components/feed/feed.mjs
> +                setTimeout(() => {
Таймаут не нужен, зачем искусственно замедлять приложение?)

2023-10-07 21:20 UTC, GreatFix commented on src/components/feed/feed.mjs
> +        (async function () {
По идее можешь из этой функции создать метод у класса (он даже уже есть, но пустой - getPosts) и передавать ему root отсюда

2023-10-08 07:55 UTC, NickDemiman commented on src/components/feed/feed.mjs
> +                setTimeout(() => {
просто хотел показать, что лоудер есть)

2023-10-08 08:58 UTC, GreatFix approved these changes
Найс

2023-10-08 08:58 UTC, merged