Issues rk1
frontend-park-mail-ru/2023_2_Rabotyagi pull request #18
Opened 2023-10-10 09:58 UTC by NickDemiman

https://github.com/frontend-park-mail-ru/2023_2_Rabotyagi/issues/13

2023-10-10 10:21 UTC, GreatFix requested changes

2023-10-10 10:21 UTC, GreatFix commented on src/index.js
> +}
Странное форматирование, настроить правило форматирования так, чтобы выглядело как было

2023-10-10 10:21 UTC, GreatFix commented on src/index.js
> +window.Router = new Router([new Route('/', new MainPage()), new Route('/signin', new SigninPage()), new Route('/signup', new SignupPage()), ]);
Здесь тоже должно выглядеть как было

2023-10-10 10:21 UTC, GreatFix commented on src/pages/signin/signin.mjs
> +            Auth.signin(inputEmail.value, inputPass.value).then(resp => {
Можно вынести здесь в метод async signin (да, я помню, что писал написать на then🙂, но в другом компоненте так сделали и здесь можно)

signup тоже

2023-10-10 10:21 UTC, GreatFix commented on src/shared/constants/store.mjs
> +                store.authorized = true;
можно просто сделать метод store.isAuth = ()=> this.user.accessToken

2023-10-10 10:21 UTC, GreatFix commented on src/shared/constants/store.mjs
> +            localStorage.removeItem('access_token');
почему localStorage ?

2023-10-10 10:21 UTC, GreatFix commented on src/shared/constants/store.mjs
> +            localStorage.setItem('access_token', token.access_token);
почему localStorage ? У вас же он хранится в куках, оттуда и берите

2023-10-10 10:21 UTC, GreatFix commented on src/shared/services/ajax.js
> +                config.body = body;
что мешает просто передать fetch(url, { body }) ? Это ко всем свойствам вопрос

2023-10-10 10:21 UTC, GreatFix commented on src/shared/utils/cookie.mjs
> +    const cookieObj = splittedPairs.reduce(function (obj, cookie) {
В reduce юзаем стрелочную функцию

2023-10-10 10:21 UTC, GreatFix commented on src/shared/utils/cookie.mjs
> +        obj[decodeURIComponent(cookie[0].trim())]
Для читаемости, можно занести decodeURIComponent(cookie[0].trim()) в переменную key, а значение в value и только потом присвоить

2023-10-10 10:21 UTC, GreatFix commented on src/shared/utils/cookie.mjs
> +    let pairs = cookieString.split(";");
В данном случае pairs не юзается ни для чего, кроме .map,  поэтому можно объединить .split().map

2023-10-10 10:21 UTC, GreatFix commented on src/shared/utils/cookie.mjs
> +    let splittedPairs = pairs.map(cookie => cookie.split("="));
Юзаем const,  где можно

2023-10-10 10:21 UTC, GreatFix commented on src/shared/utils/cookie.mjs
> +    if (cookieString === "")
- Пишем if всегда со скобками (настройте форматировшик на это)

2023-10-10 10:21 UTC, GreatFix commented on src/pages/signup/signup.mjs
> +        root = root.firstChild;
Для чего такое? Почему нельзя создать новую переменную, допустим, templateRoot ? (относится ко всем местам, где встречается)

2023-10-10 10:24 UTC, GreatFix commented
@NickDemiman  Подключи сброс стилей в проект:  https://webcademy.ru/blog/739/

2023-10-10 10:26 UTC, GreatFix commented on .prettierrc
Почему удален?

2023-10-10 10:27 UTC, GreatFix commented on docs/Api.module_Auth.html
> +      <script src="//html5shiv.googlecode.com/svn/trunk/html5.js"></script>
ie 9 поддерживаете или для чего этот коммент?

2023-10-10 10:31 UTC, NickDemiman commented on src/shared/constants/store.mjs
> +            localStorage.removeItem('access_token');
чтобы при перезагрузке сохранялось

2023-10-10 10:33 UTC, NickDemiman commented on src/pages/signup/signup.mjs
> +        root = root.firstChild;
чтобы взять внутренности не как строку а как ноду для доступа к методам объекта

2023-10-10 10:33 UTC, NickDemiman commented on .prettierrc
есть уже .prettierrc.json

2023-10-10 10:34 UTC, GreatFix commented on src/components/error/errorMessageBox.mjs
> +    return root.firstChild;
C помощью функции возвращайте корневой из шаблонизатора прямо в root. (Это относится и к остальным местам, где root создается только для получения firstChild)
https://stackoverflow.com/a/35385518

2023-10-10 10:50 UTC, GreatFix commented on src/shared/constants/store.mjs
> +            localStorage.removeItem('access_token');
Оно и в куках сохраняется при перезагрузке. Просто берите из куков, а не стораджа

2023-10-10 10:51 UTC, GreatFix commented on src/pages/signup/signup.mjs
> +        root = root.firstChild;
https://github.com/frontend-park-mail-ru/2023_2_Rabotyagi/pull/18#discussion_r1352132700

2023-10-10 16:56 UTC, NickDemiman commented
> @NickDemiman Подключи сброс стилей в проект: https://webcademy.ru/blog/739/

подключил

2023-10-10 18:18 UTC, GreatFix requested changes

2023-10-10 18:18 UTC, GreatFix commented on src/shared/constants/store.mjs
>  export const store = {
1. Вынеси, пожалуйста, файл в папку share/store/index.js
2. Стор будет разделен на модули. index будет местом объединения сторов
3. К примеру, значение свойства user выносишь в модуль user.js . В нем экспортируешь export const user = {...}. А в index импортируешь и ставишь в export const store = { user };

2023-10-10 18:18 UTC, GreatFix commented on src/shared/utils/parsing.mjs
> + * @param {String} HTML representing a single element
Раз на русском пишите комменты, то и здесь стоит так сделать

2023-10-10 18:18 UTC, GreatFix commented on src/shared/utils/cookie.mjs
> +        obj[decodeURIComponent(cookie[0].trim())] = value;
```
        const [ key, value ] = cookie;

        const decodedKey = decodeURIComponent(key.trim());
        const decodedValue = decodeURIComponent(value.trim());

        obj[decodedKey] = decodedValue;
```

2023-10-10 18:18 UTC, GreatFix commented on src/shared/utils/cookie.mjs
> +    if (cookieString === "") {
typeof cookieString !== "string" || !cookieString.length

2023-10-10 18:18 UTC, GreatFix commented on src/pages/signup/signup.mjs
> +                    if (resp.status == 200) {
Ну раз все таки решили проверять, тогда уж 
```
if (resp.status !== 200) {
  throw resp.body.error;
}
...
```

2023-10-10 18:18 UTC, GreatFix commented on src/pages/signup/signup.mjs
> +                        let cookies = cookieParser(document.cookie);
Добавьте правило в eslint, чтобы ругалось, если не используете const там, где можно

2023-10-10 18:18 UTC, GreatFix commented on src/pages/signup/signup.mjs
> +
Вот здесь по хорошему должна быть проверка, найдены ли элементы if(!inputEmail || ! || ! ) { throw error }, но это не критично на данный момент. просто на заметку

2023-10-10 18:26 UTC, GreatFix commented
Вам возможно кажется, что я сильно мелочуюсь/придираюсь, но нет, просто привожу вас потихоньку к тому уровню кода и организации этого кода, с которым сможете легко ворваться в коммерческий проект

2023-10-10 18:28 UTC, GreatFix commented on src/components/feed/feed.mjs
>  import {loaderRegular} from "../loader/loader.mjs";
Также желательно подключить правило форматирования, которое проставляет пробелы в начале и конце деструктуризации, чтобы было так: `import { loaderRegular } from "../loader/loader.mjs";`

2023-10-11 11:05 UTC, GreatFix requested changes
Расписал как наладить форматирование

2023-10-11 11:05 UTC, GreatFix commented on .eslintrc.js
> +        "prefer-const": [
Надо бы поправить это правило, чтобы не объединяло несколько подряд идущих в один const

2023-10-11 11:05 UTC, GreatFix commented on .eslintrc.js
> +            "error", {
Пусть все проблемы форматирования будут warning, а не error

2023-10-11 11:05 UTC, GreatFix commented on .prettierrc.mjs
Создай (не переименовывай) файл .prettierrc.json и перенеси туда конфиг, а это удали

2023-10-11 11:05 UTC, GreatFix commented on .vscode/settings.json
> +  "vs-code-prettier-eslint.prettierLast": false, // set as "true" to run 'prettier' last not first
добавь, чтобы автоматически правило проблемы еслинта
```
  "eslint.format.enable": true,
    "eslint.run": "onSave",
    "editor.codeActionsOnSave": {
      "source.fixAll.eslint": true
    },
  "eslint.validate": ["javascript"]
```

2023-10-11 11:05 UTC, GreatFix commented on .vscode/settings.json
> +  "editor.defaultFormatter": "rvest.vs-code-prettier-eslint",
Не нравится мне, что изменилось расширение, лучше вернуть esbenp.prettier-vscode

2023-10-11 11:05 UTC, GreatFix commented on .vscode/settings.json
Чтобы работало, должно быть установлено 2 расширения: Prettier и ESlint .  Добавь их сюда как рекомендованные расширения (погуглишь)

2023-10-11 14:36 UTC, NickDemiman commented
> Вам возможно кажется, что я сильно мелочуюсь/придираюсь, но нет, просто привожу вас потихоньку к тому уровню кода и организации этого кода, с которым сможете легко ворваться в коммерческий проект

не, мне с кайфом

2023-10-11 14:37 UTC, NickDemiman commented on .eslintrc.js
> +        "prefer-const": [
не объединяет, скорее всего на это влияло eslint:all

2023-10-11 14:38 UTC, NickDemiman commented on .eslintrc.js
>      "overrides": [
дефолтный набор правил, определенных сообществом, уже поставил recomended

2023-10-11 14:56 UTC, GreatFix commented on .eslintrc.js
>      "overrides": [
Я имел в виду overrides

2023-10-11 15:09 UTC, GreatFix requested changes
Остались некоторые комменты еще с первого ревью, на верху

2023-10-11 15:09 UTC, GreatFix commented on src/pages/signin/signin.mjs
> +                    } else {
Писать else излише, выполнение в данном случае остановится, если войдет в if

2023-10-11 15:09 UTC, GreatFix commented on src/shared/store/user.mjs
> +    setAccessToken: (token) => {
раньше было 
login:(cookie)=> {
   this.user.accessToken  = cookie.accessToken;
}
И я имел в виду привести к виду сеттера:
setAccessToken:(token)=>{
     this.user.accessToken  = token;
}

Но сейчас тут совсем иная логика получилась. Теперь можно вообще удалить setAccessToken и объединить его логику с fill (можно уже его login назвать)

2023-10-11 20:05 UTC, GreatFix requested changes

2023-10-11 20:05 UTC, GreatFix commented on src/shared/store/user.mjs
> +        }
А при перезагрузке страницы не нужно также вызвать this.login() ?

2023-10-12 06:22 UTC, NickDemiman commented on src/shared/services/ajax.js
> +                config.body = body;
Потому что мы можем сделать get запрос с параметрами, а пост запрос с get параметрами нельзя, будет браузер ругаться, поэтому попытались унифицировать

2023-10-12 07:52 UTC, GreatFix approved these changes
Огонь, молодецы

2023-10-12 07:53 UTC, merged