Mock server
frontend-park-mail-ru/2023_2_Rabotyagi pull request #24
Opened 2023-10-17 11:38 UTC by NickDemiman

2023-10-17 11:56 UTC, GreatFix requested changes

2023-10-17 11:56 UTC, GreatFix commented on src/shared/services/ajax.js
> +        addres = 'http://84.23.53.28'
Давай вместо хардкода урла, просто заюзаем process.env.API_URL

.env
`API_URL=http://84.23.53.28:8000/`

or

.env
`API_URL=http://localhost:8000/`

2023-10-17 11:56 UTC, GreatFix commented on src/shared/services/ajax.js
> +    ADRESS_BACKEND = addres + `:${this.port}/api/v1/`;
ADRESS_BACKEND = `${process.env.API_URL}/api/v1/`;

2023-10-17 11:56 UTC, GreatFix commented on src/shared/services/ajax.js
> +    /**
И в продолжении предыдущих комментом, давай добавим конструктор, который будет предупреждать, что забыли определить env переменнуя, типа:

constructor(){
```
    if(!process.env.API_URL || process.env.API_URL==="") {
        console.warning("env.API_URL .... ")    
     }

}
```

2023-10-17 11:57 UTC, GreatFix commented
И подтяните в ветку rk2 ветку dev, чтобы конфликты порешать

2023-10-17 12:34 UTC, NickDemiman commented
> И подтяните в ветку rk2 ветку dev, чтобы конфликты порешать

2 дня назад еще подтянул, сейчас не дает. говорит, что изменений нет

2023-10-17 19:00 UTC, GreatFix commented
> > И подтяните в ветку rk2 ветку dev, чтобы конфликты порешать
> 
> 2 дня назад еще подтянул, сейчас не дает. говорит, что изменений нет

тогда нужно подтянуть рк2 в свою ветку, иначе нельзя смержить, конфликты

2023-10-18 14:52 UTC, NickDemiman commented on src/shared/services/ajax.js
> +    /**
Она по дефлоту в докере в Localhost ставится, но я добавлю для NODE_ENV, мол в деве находимся

2023-10-18 16:27 UTC, GreatFix commented on src/shared/services/ajax.js
> +    /**
В докере возможно, но если локально кто-то подтянет, не сразу поймет  + это все таки сервис, если у него есть входные параметры/значения свойств берутся из вне, то должна быть проверка на это. 

Что касается лога по NODE_ENV, не вижу в нем смысла, лучше удалить.

Переменную назвать не APP_URL, а API_URL, все таки это ссылка на бэк, а не на это приложение.

Постфикс "/api/v1" лучше вернуть внутрь сервиса, а не заносить в переменную? Т.к. переменная может и для других нужд использовать и /api/v1 будет мешать (эт с точки зрения архитектуры)

2023-10-18 16:31 UTC, GreatFix commented on src/shared/services/ajax.js
> +    /**
Также создай файл .env.example, где перечисли все юзаемые переменные с комментариями и дефолт значениями для дев режиме и помести в git. Чтобы кто-то подтянул репу, переименовал файл .env.example в .env и запустил дев режим

2023-10-18 17:23 UTC, NickDemiman commented on src/shared/services/ajax.js
> +    /**
> В докере возможно, но если локально кто-то подтянет, не сразу поймет + это все таки сервис, если у него есть входные параметры/значения свойств берутся из вне, то должна быть проверка на это.
> 
> Что касается лога по NODE_ENV, не вижу в нем смысла, лучше удалить.
> 
> Переменную назвать не APP_URL, а API_URL, все таки это ссылка на бэк, а не на это приложение.
> 
> Постфикс "/api/v1" лучше вернуть внутрь сервиса, а не заносить в переменную? Т.к. переменная может и для других нужд использовать и /api/v1 будет мешать (эт с точки зрения архитектуры)

а я и не заношу постфикс в переменную, я заношу только адрес хоста

2023-10-18 18:33 UTC, GreatFix commented on src/shared/services/ajax.js
> +    /**
Соре, быканул, не увидел сначала

2023-10-22 13:08 UTC, GreatFix requested changes
1 микрокоммент

2023-10-22 13:08 UTC, GreatFix commented on .gitignore
> +package-lock.json
Давай уберем package-lock из игнора. Он нужен, чтобы при npm i устанавливались те же версии пакетов,которые были установлены при разработке

2023-10-22 16:24 UTC, GreatFix approved these changes

2023-10-22 16:24 UTC, merged